global:
  scrape_interval: 4s  

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: 
          - "10.100.19.123:8000"
          - "10.100.19.123:8001"
          - "10.100.19.123:8002"  
          
