import tensorflow as tf
import numpy as np
import random
import requests

# Load the trained RL policy
policy_dir = "saved_policies/load_balancing_trained_policy"

serverMetricsUrl = "http://localhost:8005/server-metrics"
_num_servers = 3

global SERVERS
SERVERS = [
    "http://127.0.0.1:8000",
    "http://127.0.0.1:8001",
    "http://127.0.0.1:8002"
]

try:
    agent = tf.compat.v2.saved_model.load(policy_dir)
    use_rl_model = True
    print("RL model loaded successfully.")
except Exception as e:
    print(f"Failed to load RL model: {e}")
    use_rl_model = False

def _generate_state():
    """
    Fetch performance metrics from the aggregated metrics endpoint.
    For each server, extract:
      - avg_successful_response_time (latency)
      - total_requests
      - failed_to_success_ratio
    Returns a (num_servers, 3) numpy array.
    """
    latency = []
    requests_handled = []
    failed_to_success_ratio = []
    
    try:
        response = requests.get(serverMetricsUrl)
        response.raise_for_status()
        server_metrics = response.json()
         
        for server in SERVERS:
            data = server_metrics.get(server, {})
            if "metrics" in data and data["metrics"] is not None:
                metrics = data["metrics"]
                
                print(f"{server}: {metrics}") 

                latency.append(metrics.get("avg_successful_response_time", 1.0))
                requests_handled.append(metrics.get("total_requests", 0.0))
                failed_to_success_ratio.append(metrics.get("failed_to_success_ratio", 0.5))
            else:
                print(f"No valid metrics for {server}")
                latency.append(1.0)
                requests_handled.append(0.0)
                failed_to_success_ratio.append(0.5)

    except requests.RequestException as e:
        print(f"Error fetching server metrics: {e}")
        latency = [1.0] * _num_servers
        requests_handled = [0.0] * _num_servers
        failed_to_success_ratio = [0.5] * _num_servers
    
    state = np.column_stack([latency, requests_handled, failed_to_success_ratio])

    print("State :", state)

    return state.astype(np.float32)

def select_optimal_server(servers):
    """
    Selects the optimal server using an RL model.
    Uses the state generated by _generate_state() as input to the agent's policy.
    If the model is unavailable or fails, falls back to random selection.
    
    Args:
      servers: List of available server URLs.
    
    Returns:
      Selected server (string)
    """
    # Generate state from fetched metrics (shape: [num_servers, 3])
    state_np = _generate_state()
    
    # Add batch dimension: new shape [1, num_servers, 3]
    state_tensor = tf.convert_to_tensor(state_np[np.newaxis, ...], dtype=tf.float32)
    
    if use_rl_model:
        try:
            # Get the best action from the RL model (for discrete action spaces, output shape is [batch_size, 1] or [batch_size])
            action_step = agent.policy.action(state_tensor)
            action = action_step.action.numpy()[0]  # Extract the first (and only) action from the batch
            
            # Convert to integer index if not already an integer
            selected_index = int(action) if np.isscalar(action) else int(action[0])
            print(f"RL agent selected index: {selected_index}")
             
            if 0 <= selected_index < len(servers):
                return servers[selected_index]
            else:
                print(f"Invalid action index {selected_index}, falling back to random choice.")
        except Exception as e:
            print(f"RL model inference failed: {e}")
     
    selected = random.choice(servers)

    print(f"Falling back to random selection: {selected}")

    return selected
